name: Build & Deploy

on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Loftbot
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script:
            mkdir projects
            cd projects
            git clone git@github.com:f3mshep/loftbot.git
            echo "Deployment Successful!"
