name: Build & Deploy

on:
  push:
    branches: [master]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Loftbot
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script:
            cd ~/projects/loftbot; git stash; git pull; chmod +x main.py; pip install -r requirements.txt; echo "Deployment Successful!"
